export {
  KhizaContractDict,
  arbitrum,
  avalanche,
  avalancheFuji,
  bsc,
  bscTestnet,
  fantom,
  gnosis,
  goerli,
  mainnet,
  optimismGoerli,
  polygon,
  polygonMumbai,
  sepolia,
} from "./src";

export type {
  ChainDict,
  ChainKey,
  ContractDict,
  ContractDictConfig,
  ContractType,
  CustomContract,
  KnownContract,
  KnownContractKey,
  KnownContractReturn,
  KnownContracts,
  NestedKnownContract,
  RootKnownContract,
  StopRecursion,
  TokenContract,
} from "./src";
